# Generated by Django 4.0.5 on 2022-06-26 15:46

import app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(default=app.models.random_string, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('01d2f0ce-8f47-56e4-9a9c-0f368406feb7'), editable=False),
        ),
    ]
