# Generated by Django 4.0.5 on 2022-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_payment_ref_order_payment_status_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
